# --> HeadPlugin <--
# Author: finleyjoel1/Kixaux
# Made with â¤ | 2025
# --> HeadPlugin <--

#% name% is the name of the plugin
permissions:
  useCommand: '%name%.command.use'
  useGui: '%name%.gui.use'
settings:
  language: en
  prefix: '&x&5&4&A&6&F&4&lH&x&5&4&A&6&F&4&le&x&5&4&A&6&F&4&la&x&5&4&A&6&F&4&ld&x&7&1&B&5&F&6&lP&x&8&D&C&4&F&8&ll&x&A&A&D&3&F&A&lu&x&C&6&E&1&F&B&lg&x&E&3&F&0&F&D&li&x&F&F&F&F&F&F&ln
    &8| &7'
